[env:matrixportal_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Matrix Portal S3: 8 MB flash, 2 MB PSRAM.
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

lib_deps =
    adafruit/Adafruit Protomatter
    adafruit/Adafruit GFX Library
    fastled/FastLED
